##04_로지스틱회귀분류_규제 강도 비교

In [ ]:
import pandas as pd
import numpy as np

###1. 데이터셋 불러오기
  - y 값은 이미 범주형이므로 데이터 카테고리 실수화 생략

In [ ]:
dat_wine=pd.read_csv('http://archive.ics.uci.edu/ml/machine-learning-databases/wine/wine.data',header=None)

dat_wine.head()
dat_wine.columns = ['class label', 'alchohol', 'malic acid', 'ash',
                    'alcalinity of ash', 'magnesium', 'total phenols', 
                    'flavanoids', 'nonflavanoid phenols', 
                    'proanthocyanins', 'color intensity', 'hue', 
                    'OD208', 'proline'] # column names
print('class label: ', np.unique(dat_wine['class label']))
dat_wine.head()

class label:  [1 2 3]


class label  alchohol  malic acid  ...   hue  OD208  proline
0            1     14.23        1.71  ...  1.04   3.92     1065
1            1     13.20        1.78  ...  1.05   3.40     1050
2            1     13.16        2.36  ...  1.03   3.17     1185
3            1     14.37        1.95  ...  0.86   3.45     1480
4            1     13.24        2.59  ...  1.04   2.93      735

[5 rows x 14 columns]

###3. 데이터 분할

In [ ]:
from sklearn.model_selection import train_test_split
X = dat_wine.iloc[:,1:].values
y = dat_wine.iloc[:,0].values
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size = 0.3, random_state = 1, stratify = y)

###4. 입력 데이터의 표준화

In [ ]:
from sklearn.preprocessing import StandardScaler
std = StandardScaler()
X_train_std = std.fit_transform(X_train)
X_test_std = std.fit_transform(X_test)

###5. 모델 추정: Logistic Regression
Logistic Regression with L2 or L1 Regularization



In [ ]:
from sklearn.linear_model import LogisticRegression

# L2 with various Cs
lr2_10 = LogisticRegression(penalty = 'l2', C = 10.0, solver = 'saga') # L2 with C(=1/λ)=10
lr2_1 = LogisticRegression(penalty = 'l2', C = 1.0, solver = 'saga') # L2 with C(=1/λ)=1
lr2_0_1 = LogisticRegression(penalty = 'l2', C = 0.1, solver = 'saga') # L2 with C(=1/λ)=0.1

# L1 with various Cs
lr1_10 = LogisticRegression(penalty = 'l1', C = 10.0, solver = 'saga') # L1 with C(=1/λ)=10
lr1_1 = LogisticRegression(penalty = 'l1', C = 1.0, solver = 'saga') # L1 with C(=1/λ)=1
lr1_0_1 = LogisticRegression(penalty = 'l1', C = 0.1, solver = 'saga') # L1 with C(=1/λ)=0.1

###6. 결과 분석
규제화 방법(L2 or L1)과 규제강도(λ)를 바꿔가며 정확도 계산 및 비교

In [ ]:
lr2_10.fit(X_train_std, y_train)
print('Training accuracy with L2 and λ=0.1:', lr2_10.score(X_train_std, y_train))
print('Test accuracy with L2 and λ=0.1:', lr2_10.score(X_test_std, y_test))

lr2_1.fit(X_train_std, y_train)
print('Training accuracy with L2 and λ=1:', lr2_1.score(X_train_std, y_train))
print('Test accuracy with L2 and λ=1:', lr2_1.score(X_test_std, y_test))

lr2_0_1.fit(X_train_std, y_train)
print('Training accuracy with L2 and λ=10:', lr2_0_1.score(X_train_std, y_train))
print('Test accuracy with L2 and λ=10:', lr2_0_1.score(X_test_std, y_test))

lr1_10.fit(X_train_std, y_train)
print('Training accuracy with L1 and λ=0.1:', lr1_10.score(X_train_std, y_train))
print('Test accuracy with L1 and λ=0.1:', lr1_10.score(X_test_std, y_test))

lr1_1.fit(X_train_std, y_train)
print('Training accuracy with L1 and λ=1:', lr1_1.score(X_train_std, y_train))
print('Test accuracy with L1 and λ=1:', lr1_1.score(X_test_std, y_test))

lr1_0_1.fit(X_train_std, y_train)
print('Training accuracy with L1 and λ=10:', lr1_0_1.score(X_train_std, y_train))
print('Test accuracy with L1 and λ=10:', lr1_0_1.score(X_test_std, y_test))

Training accuracy with L2 and λ=0.1: 1.0
Test accuracy with L2 and λ=0.1: 0.9629629629629629
Training accuracy with L2 and λ=1: 1.0
Test accuracy with L2 and λ=1: 0.9814814814814815
Training accuracy with L2 and λ=10: 1.0
Test accuracy with L2 and λ=10: 0.9814814814814815
Training accuracy with L1 and λ=0.1: 1.0
Test accuracy with L1 and λ=0.1: 0.9814814814814815
Training accuracy with L1 and λ=1: 1.0
Test accuracy with L1 and λ=1: 0.9814814814814815
Training accuracy with L1 and λ=10: 0.967741935483871
Test accuracy with L1 and λ=10: 0.9629629629629629


/usr/local/lib/python3.7/dist-packages/sklearn/linear_model/_sag.py:330: ConvergenceWarning: The max_iter was reached which means the coef_ did not converge
  "the coef_ did not converge", ConvergenceWarning)
/usr/local/lib/python3.7/dist-packages/sklearn/linear_model/_sag.py:330: ConvergenceWarning: The max_iter was reached which means the coef_ did not converge
  "the coef_ did not converge", ConvergenceWarning)
/usr/local/lib/python3.7/dist-packages/sklearn/linear_model/_sag.py:330: ConvergenceWarning: The max_iter was reached which means the coef_ did not converge
  "the coef_ did not converge", ConvergenceWarning)
/usr/local/lib/python3.7/dist-packages/sklearn/linear_model/_sag.py:330: ConvergenceWarning: The max_iter was reached which means the coef_ did not converge
  "the coef_ did not converge", ConvergenceWarning)


L2 규제의 규제 강도(C=1/λ)를 바꿔가며 계수 추정치 관찰

In [ ]:
#모델의 기울기
print(lr2_10.intercept_)
print(lr2_1.intercept_)
print(lr2_0_1.intercept_)

#모델의 절편
print(lr2_10.coef_)
print(lr2_1.coef_)
print(lr2_0_1.coef_)

[ 0.31860509  0.64346784 -0.96207293]
[ 0.28376708  0.60390172 -0.8876688 ]
[ 0.06843359  0.45685509 -0.52528868]
[[ 1.25788632  0.17760598  0.35657628 -1.54761812  0.13757124  0.37280048
   0.91050525 -0.3079761   0.03435118  0.1528233   0.08933145  0.99168296
   1.31331094]
 [-1.56479148 -0.4383257  -1.27003584  1.24535438 -0.34090466 -0.51257479
   0.82362412  0.41488584  0.42061542 -1.32437357  1.14215782  0.04271079
  -1.69749997]
 [ 0.30690516  0.26071972  0.91345956  0.30226374  0.20333342  0.13977431
  -1.73412938 -0.10690974 -0.45496659  1.17155027 -1.23148927 -1.03439375
   0.38418902]]
[[ 0.75467373  0.06156123  0.233273   -0.89235189  0.02628102  0.29428773
   0.560916   -0.20729873  0.13438551  0.12796929  0.10222944  0.61792633
   0.90942118]
 [-0.98659744 -0.32322533 -0.65172223  0.66768203 -0.22947405 -0.20700797
   0.43825474  0.19827681  0.24418201 -0.78011296  0.63731846  0.0857639
  -1.03439577]
 [ 0.23192371  0.26166409  0.41844922  0.22466985  0.20319302 -0.087279

L1 규제의 규제강도(C=1/λ)를 바꿔가며 계수 추정치 관찰

In [ ]:
#모델의 기울기
print(lr1_10.intercept_)
print(lr1_1.intercept_)
print(lr1_0_1.intercept_)

#모델의 절편
print(lr1_10.coef_)
print(lr1_1.coef_)
print(lr1_0_1.coef_)

[ 0.34752147  0.65468189 -1.00220336]
[ 0.28973949  0.53659442 -0.82633391]
[ 0.05084395  0.30693006 -0.35777401]
[[ 1.21569089  0.          0.20294765 -1.60177534  0.          0.20391338
   0.79431772 -0.13182987  0.          0.          0.          0.9194363
   1.51657738]
 [-1.80439471 -0.40141874 -1.48865361  1.07153443 -0.32317319 -0.42415058
   0.67400058  0.39069184  0.21116892 -1.40320993  1.17333606  0.
  -1.98759694]
 [ 0.06120671  0.17626697  0.75854917  0.00512603  0.20963114  0.
  -1.99573033  0.         -0.39259069  1.15392494 -1.22653394 -0.96209286
   0.        ]]
[[ 0.02872355  0.          0.         -1.17742433  0.          0.
   0.02959819  0.          0.          0.          0.          0.62434593
   0.96314921]
 [-1.57124778 -0.14944645 -0.76643108  0.03893103 -0.06807047  0.
   0.          0.13559967  0.         -1.04316161  0.21990128  0.
  -1.22147589]
 [ 0.          0.          0.          0.          0.          0.
  -2.0828414   0.         -0.03416089  0.2310