##11_선형회귀_Linear Regression

### ML/DL 라이브러리 불러오기

PyTorch

In [ ]:
import torch
import torch.optim as optim

Random Seed 고정하기

In [ ]:
torch.manual_seed(1)

###1. 데이터셋 불러오기

(x1, y1) = (1, 1)   (x2, y2) = (2, 2)   (x3, y3) = (3, 3)


In [ ]:
x_train = torch.FloatTensor([[1], [2], [3]])
y_train = torch.FloatTensor([[1], [2], [3]])

In [ ]:
print(x_train)
print(x_train.shape)

tensor([[1.],
        [2.],
        [3.]])
torch.Size([3, 1])


In [ ]:
print(y_train)
print(y_train.shape)

tensor([[1.],
        [2.],
        [3.]])
torch.Size([3, 1])


기본적으로 Pytorch는 NCHW 형태이다<br>
N: n-count(batch)<br>
C: Channel<br>
H: Height<br>
W: Width<br>

###5. 모델 추정

####Weight Initialization

In [ ]:
# 1x1 행렬, 0으로 초기화
W = torch.zeros(1, requires_grad = True) #requires_grad=True : 학습용 변수라고 명시적 초기화

print(W)

tensor([0.], requires_grad=True)


In [ ]:
b = torch.zeros(1, requires_grad = True)

print

tensor([0.], requires_grad=True)


####Hypothesis

$$ H(x) = Wx + b $$

In [ ]:
hypothesis = x_train * W +b

print(hypothesis)

tensor([[0.],
        [0.],
        [0.]], grad_fn=<AddBackward0>)


####Cost

$$ cost(W, b) = \frac{1}{m} \sum^m_{i=1} \left( H(x^{(i)}) - y^{(i)} \right)^2 $$

In [ ]:
cost = torch.mean((hypothesis - y_train) ** 2)
print(cost)

tensor(4.6667, grad_fn=<MeanBackward0>)


#### Gradient Descent

In [ ]:
optimizer = optim.SGD([W, b], lr = 0.01) #lr(learning rate) = alpha

$$ W := W - \alpha \frac{\partial}{\partial W} cost(W, b) $$

Optimizer 초기화

In [ ]:
optimizer.zero_grad()

cost 계산 = 미분값 계산하기

In [ ]:
cost.backward()

Optimizer 갱신 = W, b 갱신

In [ ]:
optimizer.step()

갱신 전 후 비교

In [ ]:
hypothesis = x_train * W + b

print(hypothesis)

tensor([[0.1333],
        [0.2267],
        [0.3200]], grad_fn=<AddBackward0>)


In [ ]:
cost = torch.mean((hypothesis - y_train)**2)

print(cost)

tensor(3.6927, grad_fn=<MeanBackward0>)


### Full Code with 갱신 반복

In [ ]:
# 데이터셋 불러오기
x_train = torch.FloatTensor([[1], [2], [3]])
y_train = torch.FloatTensor([[1], [2], [3]])

# 모델 초기화
W = torch.zeros(1, requires_grad=True)
b = torch.zeros(1, requires_grad=True)

# Optimizer 설정
optimizer = optim.SGD([W, b], lr=0.01)

# 파라미터 갱신 1000번 갱신 반복하기
nb_epochs = 1000
for epoch in range(nb_epochs + 1):

  # Hypothesis
  hypothesis = x_train * W + b

  # Cost
  cost = torch.mean((hypothesis - y_train) ** 2)

  # Cost로 파라미터 W, b 갱신
  optimizer.zero_grad()
  cost.backward()
  optimizer.step()

  # 100번마다 갱신 상황 출력
  if epoch % 100 == 0:
    print('Epoch {:4d}/{} W: {:.3f}, b: {:.3f}, Cost: {:.6f}'.format(epoch, nb_epochs, W.item(), b.item(), cost.item()))


Epoch    0/1000 W: 0.093, b: 0.040, Cost: 4.666667
Epoch  100/1000 W: 0.873, b: 0.289, Cost: 0.012043
Epoch  200/1000 W: 0.900, b: 0.227, Cost: 0.007442
Epoch  300/1000 W: 0.921, b: 0.179, Cost: 0.004598
Epoch  400/1000 W: 0.938, b: 0.140, Cost: 0.002842
Epoch  500/1000 W: 0.951, b: 0.110, Cost: 0.001756
Epoch  600/1000 W: 0.962, b: 0.087, Cost: 0.001085
Epoch  700/1000 W: 0.970, b: 0.068, Cost: 0.000670
Epoch  800/1000 W: 0.976, b: 0.054, Cost: 0.000414
Epoch  900/1000 W: 0.981, b: 0.042, Cost: 0.000256
Epoch 1000/1000 W: 0.985, b: 0.033, Cost: 0.000158
