#12_선형분류_이진분류

### ML/DL 라이브러리 불러오기

In [1]:
import torch
import torch.optim as optim
# random Seed 고정하기
torch.manual_seed(1)

##1. 데이터셋불러오기

In [2]:
x_data = [[1, 2], [2, 3], [3, 1], [4, 3], [5, 3], [6, 2]]
y_data = [[0], [0], [0], [1], [1], [1]]

In [3]:
x_train = torch.FloatTensor(x_data)
y_train = torch.FloatTensor(y_data)

In [4]:
print(x_data)
print(x_train)

[[1, 2], [2, 3], [3, 1], [4, 3], [5, 3], [6, 2]]
tensor([[1., 2.],
        [2., 3.],
        [3., 1.],
        [4., 3.],
        [5., 3.],
        [6., 2.]])


In [5]:
print(x_train.shape)
print(y_train.shape)

torch.Size([6, 2])
torch.Size([6, 1])


##5. 모델 학습: 이진분류 & Sigmoid

Sigmoid Hypothesis
$$ H(X) = \frac{1}{1+e^{-W^T X}} $$

Cost of Sigmoid Hypothesis
$$ cost(W) = -\frac{1}{m} \sum y \log\left(H(x)\right) + (1-y) \left( \log(1-H(x) \right) $$

Gradient Descent($\alpha$ == learning rate)
$$ W := W - \alpha \frac{\partial}{\partial W} cost(W) $$

In [6]:
#2차원 입력데이터 -> 출력 0 or 1

# Initialization: W and b
W = torch.zeros((2, 1), requires_grad = True)
b = torch.zeros(1, requires_grad = True)

# Opimizer
optimizer = optim.SGD([W, b], lr = 1)

# 파라미커 100번 갱신 반복하기
nb_epochs = 1000
for epoch in range(nb_epochs + 1):

  # Sigmoid Hypothesis
  hypothesis = torch.sigmoid(x_train.matmul(W)+b)

  # Cost
  cost = -(y_train*torch.log(hypothesis) + (1 - y_train) * torch.log(1 - hypothesis)).mean()

  # Cost로 파라미터 W, b 갱신
  optimizer.zero_grad() # Optimizer의 gradient을 0으로 초기화
  cost.backward() # Cost로 optimizer 알고리즘 수행
  optimizer.step() # W, b 갱신

  #100번마다 갱신 상황 출력
  if epoch % 100 == 0:
    print('Epoch {:4d}/{} Cost: {:.6f}'.format(epoch, nb_epochs, cost.item()))

Epoch    0/1000 Cost: 0.693147
Epoch  100/1000 Cost: 0.134722
Epoch  200/1000 Cost: 0.080643
Epoch  300/1000 Cost: 0.057900
Epoch  400/1000 Cost: 0.045300
Epoch  500/1000 Cost: 0.037261
Epoch  600/1000 Cost: 0.031673
Epoch  700/1000 Cost: 0.027556
Epoch  800/1000 Cost: 0.024394
Epoch  900/1000 Cost: 0.021888
Epoch 1000/1000 Cost: 0.019852


##6. 결과 분석

Sigmoid Hypothesis

In [7]:
hypothesis = torch.sigmoid(x_train.matmul(W) + b)

print(hypothesis[:5])

tensor([[2.7648e-04],
        [3.1608e-02],
        [3.8977e-02],
        [9.5622e-01],
        [9.9823e-01]], grad_fn=<SliceBackward>)


0.5 기준으로 예측값을 0 or 1로 나누기

In [8]:
prediction = hypothesis >= torch.FloatTensor([0.5])

print(prediction[:5])

tensor([[False],
        [False],
        [False],
        [ True],
        [ True]])


정답

In [9]:
print(y_train)

tensor([[0.],
        [0.],
        [0.],
        [1.],
        [1.],
        [1.]])


채점

In [10]:
correct_prediction = prediction.float() == y_train

print(correct_prediction[:5])

tensor([[True],
        [True],
        [True],
        [True],
        [True]])


정확도

In [11]:
accuracy = correct_prediction.sum().item() / len(correct_prediction)
print('The model has an accuracy of {:2.2f}% for the training set'.format(accuracy * 100))

The model has an accuracy of 100.00% for the training set


만약 100시간 공부하고 5번 수업에 참여했을때 Pass? or Nonpass?

In [12]:
# 새로운 데이터
XX = [[100, 5]]
xx= torch.FloatTensor(XX)

# 모델이 넣기
hypothesis = torch.sigmoid(xx.matmul(W)+b)

# 예측
prediction = hypothesis >= torch.FloatTensor([0.5])

print(prediction)

tensor([[True]])
